AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**/*'
  - 'db/schema.rb'
  - 'db/migrate/20220529161953_devise_create_users.rb'

Style/Documentation:
  Exclude:
  - 'db/migrate/*.rb'
  - 'db/migrate_reports/*.rb'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'
  - 'config/environments/*.rb'
