---
version: '3.7'
services:
  database:
    image: library/postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: "/var/pgdata"
    networks:
      local:
        aliases:
        - database
    ports:
    - 51053:5432
    volumes:
    - database:/var/pgdata
  database-reports:
    image: library/postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: "/var/pgdata"
    networks:
      local:
        aliases:
        - database-reports
    ports:
    - 33251:5432
    volumes:
    - database-reports:/var/pgdata
  redis:
    image: library/redis:7.0
    networks:
      local:
        aliases:
        - redis
    ports:
    - 41149:6379
volumes:
  database: {}
  database-reports: {}
networks:
  local:
    name: "${COMPOSE_PROJECT_NAME}"
