---
version: '3.7'
services:
  database:
    image: library/postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: "/var/pgdata"
    networks:
      local:
        aliases:
        - database
    ports:
    - "${sidecar-55421:}5432"
  database-reports:
    image: library/postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: "/var/pgdata"
    networks:
      local:
        aliases:
        - database-reports
    ports:
    - "${sidecar-33250:}5432"
  redis:
    image: library/redis:7.0
    networks:
      local:
        aliases:
        - redis
    ports:
    - "${sidecar-42845:}6379"
volumes: {}
networks:
  local:
    name: "${COMPOSE_PROJECT_NAME}"
