---
version: '3.7'
services:
  database:
    image: library/postgres:14
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: "/var/pgdata"
    networks:
      local:
        aliases:
        - database
    ports:
    - "${sidecar-33249:}5432"
  database-reports:
    image: library/postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: "/var/pgdata"
    networks:
      local:
        aliases:
        - database-reports
    ports:
    - "${sidecar-33250:}5432"
volumes: {}
networks:
  local:
    name: "${COMPOSE_PROJECT_NAME}"
